extends:
  - standard
  - standard-react
  - prettier

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    -
      trailingComma: none
      singleQuote: true
      semi: false

env:
  es6: true